[tool.poetry]
name = "unbound-keycontrol-client-api"
version = "0.2.0"
description = ""
authors = ["Jerod Gawne <jerodgawne@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.5.3"
base-client-api = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.11.1"
pytest-runner = "^5.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
